### ISSUE TITLE
First child border style overwritten

### ISSUE THREAD

**Issue by Fraham** [rhyneav/papercss#6]
When the first child border has custom styles, for example border colour, this style is overwritten by the initial border styling
```css
.border, .border-1, .child-borders > *:nth-child(6n+1) {
    border: 2px solid @primary;
    border-top-left-radius: 255px 15px;
    border-top-right-radius: 15px 225px;
    border-bottom-right-radius: 225px 15px;
    border-bottom-left-radius: 15px 255px;
}
```
